---
title: "Dictionary"
author: "Annie"
date: "February 23, 2019"
output:
  html_document: default
---

#Dictionary

##General bits
1. help(topic)


2. ?topic

3. ls()
4. dir()
5. list.files()

##Input and output
save()
load()
data()
library()
-This code allows you to access a package and insert it into your code. Then it allows your package to work for the code chunk.
ex.
```{r}
library(ggplot2)
Names <- rep(c("Dara", "Azalea", "Barbi", "Rowena", "Fiona"),each=2)
MF <- rnorm(10, 45, 25)
Condition <- rep(c("Social", "Nonsocial"), 5)
Aversity <- rep(c("A", "N_A"), times=c(4,6))
plot_df <- data.frame (Names, MF, Condition, Aversity)

ggplot(plot_df, aes(x=Condition, y=MF, group=Names, 
                    linetype=Aversity))

```
read.table()
read.csv()
scan()
print()
cat()
write.table()

##Data Creation
c()
from:to (where from and to are replaced with numbers, e.g. 1:10)
seq()
rep()
data.frame()
list()
matrix()
factor()
rbind()
cbind()

##Slicing and extracting data indexing vectors
x[n] nth element
x[-n] all but nth element
x[1:n] first n elements
x[-(1:n)] elements from n+1 to the end
x[c(1,4,2)] specific elements
x[“name”] elements named “name”
x[x>3] all elements greater than 3
x[x > 3 & x < 5] all elements between 3 and 5
x[x %in% c(“a”,“and”,“the”)] all elements in given set

##Indexing lists
x[n] list with elements n
x[[n]] nt h element of the list
x[[“name”]] element of the list named “name”
x$name id.

##Indexing matrices
x[i,j] element at row i, column j
x[i,] row i
x[,j] column j
x[,c(1,3)] columns 1 and 3
x[“name”,] row named “name”
Indexing data frames (matrix indexing plus the following)
x[[“name”]] column named “name”
x$nameid.

##Variable conversion
as.data.frame(x)
as.numeric(x)
as.logical(x)
as.character(x)

##Variable information
is.na(x)
is.null(x)
is.data.frame(x)
is.numeric(x)
is.character(x)
length(x)
dim(x)
dimnames(x)
nrow(x)
ncol(x)
class()
attributes()

##Data selection and manipulation
which.max()
which.min()
which()
sort()
unique()
table()
sample()
Math
max()
min()
range()
sum()
mean()
median()
var()
sd()
cor()
round()
abs()

##Matrices
t()
diag()
rowSums()
colSums()
rowMeans()
colMeans()

##Advanced Data processing
apply()
aggregate()
Strings
paste()
strsplit()
tolower()
toupper
Plotting
hist()
plot()
Distributions
rnorm()
runif()

##Programming
show that you can define a function
show that you can write a for loop
show that you can write a while loop
show that you can write an if else statement
Explain what return() does inside a function, show you can use it
Explain what break() does, show you can use it

##Installing some packages
Use the packages tab in R-studio to install these packages. You will need to be connected to the internet when you do this. If you are installing on your laptop, or on R-studio Cloud, then these packages will not need to installed again.

ggplot2
dplyr
shiny
data.table
reshape2
stringr
